### ISSUE TITLE
Henvis til forum.m5stack.com og evt. en mulighed for at sende en mail til os

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/M5Guide#13]
Vi skal overveje hvordan gymnasieelever og lærere kommer i kontakt med os løbende. En Discord? Et Discourse forum?

Til en start kan vi henvise til m5stack's forum.

**Comment by Majahh** [comment]
Jeg tænker vi skal henvise til forum.dataekspeditioner.dk, nu hvor det er lavet, right?

**Comment by Majahh** [comment]
lagt under fejlsøgning
